# Generated by Django 5.2 on 2025-04-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_excel_comparison', '0003_alter_fileupload_related_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='related_file',
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField()),
                ('file1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file1_comparisons', to='project_excel_comparison.fileupload')),
                ('file2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file2_comparisons', to='project_excel_comparison.fileupload')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10)),
                ('column_name', models.CharField(max_length=255)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_changes', to='project_excel_comparison.comparison')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_columns_file1', models.IntegerField()),
                ('total_columns_file2', models.IntegerField()),
                ('common_columns', models.IntegerField()),
                ('added_columns', models.IntegerField()),
                ('removed_columns', models.IntegerField()),
                ('total_rows_file1', models.IntegerField()),
                ('total_rows_file2', models.IntegerField()),
                ('added_rows', models.IntegerField()),
                ('removed_rows', models.IntegerField()),
                ('changed_values', models.IntegerField()),
                ('comparison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='project_excel_comparison.comparison')),
            ],
        ),
        migrations.CreateModel(
            name='RowChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10)),
                ('row_data', models.JSONField()),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_changes', to='project_excel_comparison.comparison')),
            ],
        ),
        migrations.CreateModel(
            name='ValueDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_row_file1', models.IntegerField()),
                ('excel_row_file2', models.IntegerField()),
                ('column', models.CharField(max_length=255)),
                ('file1_value', models.TextField()),
                ('file2_value', models.TextField()),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_differences', to='project_excel_comparison.comparison')),
            ],
        ),
    ]
