# Generated by Django 5.2 on 2025-04-05 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_excel_comparison', '0004_remove_fileupload_related_file_comparison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonsummary',
            name='comparison',
        ),
        migrations.RemoveField(
            model_name='rowchange',
            name='comparison',
        ),
        migrations.RemoveField(
            model_name='valuedifference',
            name='comparison',
        ),
        migrations.AddField(
            model_name='comparison',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ColumnChange',
        ),
        migrations.DeleteModel(
            name='ComparisonSummary',
        ),
        migrations.DeleteModel(
            name='RowChange',
        ),
        migrations.DeleteModel(
            name='ValueDifference',
        ),
    ]
