# Generated by Django 5.2.1 on 2025-06-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_excel_comparison', '0010_comparison_range1_comparison_range2'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='column1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='column2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
