# Generated by Django 5.1.7 on 2025-04-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_excel_comparison', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
