# Generated by Django 5.2 on 2025-04-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_excel_comparison', '0006_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_delete_files',
            field=models.BooleanField(default=False),
        ),
    ]
