# Generated by Django 5.2 on 2025-04-15 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_excel_comparison', '0008_database_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database_Comparison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schema1', models.CharField(max_length=255)),
                ('schema2', models.CharField(max_length=255)),
                ('table1', models.CharField(max_length=255)),
                ('table2', models.CharField(max_length=255)),
                ('primary_key1', models.CharField(max_length=255)),
                ('primary_key2', models.CharField(max_length=255)),
                ('results', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('connection1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_comparisons', to='project_excel_comparison.database_connection')),
                ('connection2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_comparisons', to='project_excel_comparison.database_connection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
